/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package appliswap;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Teckos
 */
public class JFrameModification extends javax.swing.JFrame {

    Statement stm;
    connexion maConnexion=new connexion();
    ResultSet rs;
    ResultSet rs1;
    /**
     * Creates new form JFrameModification
     */
     
  
    public JFrameModification() {
        initComponents();
        imei.setDocument(new JTextFieldLimit(17));
        code.setEnabled(false);
        operateur.setEnabled(false);
        N_REP.setEnabled(false);
        imeiori.setEnabled(false);
        ups.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        imei = new javax.swing.JTextField();
        code = new javax.swing.JTextField();
        modifier = new javax.swing.JButton();
        chercher = new javax.swing.JButton();
        operateur = new javax.swing.JTextField();
        supprimer = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        N_REP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        imeiori = new javax.swing.JTextField();
        ups = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MODIFICATION APPAREILS SWAPPÉS");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(380, 330));

        jLabel1.setText("Opérateur :");

        jLabel2.setText("IMEI :");

        jLabel3.setText("Code Apple :");

        imei.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                imeiFocusGained(evt);
            }
        });
        imei.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imeiMouseClicked(evt);
            }
        });
        imei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imeiActionPerformed(evt);
            }
        });
        imei.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                imeiKeyPressed(evt);
            }
        });

        modifier.setText("Modifier");
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });

        chercher.setText("Chercher");
        chercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chercherActionPerformed(evt);
            }
        });
        chercher.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                chercherKeyPressed(evt);
            }
        });

        supprimer.setText("Supprimer");
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });

        jLabel5.setText("N Réparation :");

        jLabel4.setForeground(java.awt.Color.gray);
        jLabel4.setText("IMEI Original :");

        imeiori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imeioriActionPerformed(evt);
            }
        });

        jLabel6.setText("Tracking UPS :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(imei, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chercher)
                        .addGap(33, 33, 33)
                        .addComponent(modifier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(supprimer))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(imeiori)
                            .addComponent(code, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(N_REP)
                            .addComponent(operateur)
                            .addComponent(ups, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(imei, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(imeiori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ups, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(N_REP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(operateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chercher)
                    .addComponent(modifier)
                    .addComponent(supprimer))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(375, 370));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chercher(){
        
      String IMEI = imei.getText();
        code.setEnabled(true);
        operateur.setEnabled(true);
        N_REP.setEnabled(true);
        imeiori.setEnabled(true);
        ups.setEnabled(true);
        
        imeiori.setText("");
        code.setText("");
        operateur.setText("");
            N_REP.setText("");
            ups.setText("");
            if ((IMEI.length() == 17)&(IMEI.startsWith("A"))&(IMEI.endsWith("B")))
                          {
                              IMEI=IMEI.substring(1, 16);
                              imei.setText(IMEI);
                          }
 /*       if(IMEI.length() != 15 ){
            JOptionPane.showMessageDialog(null,"Le champs IMEI doit avoir 15 caractères");
            imei.setText("");
            //code.setText("");
            imei.requestFocusInWindow();
        }
  */          
 //       else {
            //la requête
            String requete="select * from réparation where IMEI_NEW = " + IMEI ;
        
            //Exécuter la requête
            try{
                stm=maConnexion.get_connexion().createStatement();
                rs=stm.executeQuery(requete); 
                //stm.executeUpdate(requete); 
                while(rs.next()){
                    code.setText(rs.getString("CodeAPPLE"));
                    operateur.setText(rs.getString("Opérateur"));
                    N_REP.setText(rs.getString("N_REP"));
                    ups.setText(rs.getString("UPS"));
                    String id=rs.getString("ID");
                    String requete1="select IMEI_ORI from liste_swap where id = " + id ;
                    stm=maConnexion.get_connexion().createStatement();
                    rs1=stm.executeQuery(requete1);
                     while(rs1.next()){
                        imeiori.setText(rs1.getString("IMEI_ORI"));
                    }
                }
                 
                   
            }
            catch(SQLException e){
                //System.err.println(e);
                java.awt.Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(null, e);
            }
 //       }   
    }
    
    private void chercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chercherActionPerformed
        chercher();
    }//GEN-LAST:event_chercherActionPerformed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
        // TODO add your handling code here:
        String CODE = code.getText();
       
        String OPERATEUR = operateur.getText();
      
        String IMEI = imei.getText();
        
        String N_Rep = N_REP.getText();
        
        String UPS = ups.getText();
               
        //la requête
        String requete="UPDATE réparation set CodeAPPLE='"+CODE+"',Opérateur = '"+OPERATEUR+"', N_REP ='"+N_Rep+"', UPS ='"+UPS+"' where IMEI_NEW = '"+IMEI+"'" ;
        
        //Exécuter la requête
       try{
            stm=maConnexion.get_connexion().createStatement();
            // stm.executeQuery(requete); ne passe pas pour l'insertion dans mysql
            stm.executeUpdate(requete); 
        
            JOptionPane.showMessageDialog(null,"la modification est effectué ! ");
            code.setText("");
            imei.setText(""); 
            operateur.setText("");
            N_REP.setText("");
            imeiori.setText("");
            ups.setText("");
            imei.requestFocusInWindow();
  
       }
        catch(SQLException e){
           //System.err.println(e);
            java.awt.Toolkit.getDefaultToolkit().beep();
           JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_modifierActionPerformed

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        // TODO add your handling code here:
        String CODE = code.getText();
       
        String OPERATEUR = operateur.getText();
      
        String IMEI = imei.getText();
        
        String N_Rep = N_REP.getText();
               
        //la requête
        String requete="UPDATE réparation SET Opérateur ='', N_BL='0' where IMEI_NEW = '"+IMEI+"'" ;
        
        //Exécuter la requête
        try{
            stm=maConnexion.get_connexion().createStatement();
            // stm.executeQuery(requete); ne passe pas pour l'insertion dans mysql
            stm.executeUpdate(requete); 
        
            JOptionPane.showMessageDialog(null,"la suppression est effectuée ! ");
            code.setText("");
            imei.setText(""); 
            operateur.setText("");
            N_REP.setText("");
            imeiori.setText("");
            ups.setText("");
            imei.requestFocusInWindow();
            //code.setEnabled(false);
            //operateur.setEnabled(false);
        }
        catch(SQLException e){
           //System.err.println(e);
            java.awt.Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_supprimerActionPerformed

    private void chercherKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chercherKeyPressed
        // TODO add your handling code here:
     
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        chercher(); 
         }   
    }//GEN-LAST:event_chercherKeyPressed

    private void imeiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_imeiKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            
            chercher();
        }
    }//GEN-LAST:event_imeiKeyPressed

    private void imeiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imeiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imeiActionPerformed

    private void imeioriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imeioriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imeioriActionPerformed

    private void imeiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_imeiFocusGained
        code.setText("");
            imei.setText(""); 
            operateur.setText("");
            N_REP.setText("");
            imeiori.setText("");
            ups.setText("");
    }//GEN-LAST:event_imeiFocusGained

    private void imeiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imeiMouseClicked
        code.setText("");
            imei.setText(""); 
            operateur.setText("");
            N_REP.setText("");
            imeiori.setText("");
            ups.setText("");
    }//GEN-LAST:event_imeiMouseClicked
              
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameModification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameModification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameModification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameModification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameModification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField N_REP;
    private javax.swing.JButton chercher;
    private javax.swing.JTextField code;
    private javax.swing.JTextField imei;
    private javax.swing.JTextField imeiori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton modifier;
    private javax.swing.JTextField operateur;
    private javax.swing.JButton supprimer;
    private javax.swing.JTextField ups;
    // End of variables declaration//GEN-END:variables
}
