/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package appliswap;

import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Teckos
 */
public class JFrameAppareil extends javax.swing.JFrame {
    Statement stm;
    private PreparedStatement pst;
    ResultSet rs;
    connexion maConnexion= new connexion();

    /**
     * Creates new form JFrameAppareil
     */
    public JFrameAppareil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        code = new javax.swing.JTextField();
        cap = new javax.swing.JTextField();
        coul = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        type = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GESTION CODES APPLE");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Code APPLE :");

        jLabel3.setText("Capacité :");

        jLabel4.setText("Couleur :");

        jButton1.setText("Créer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        code.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                codeFocusGained(evt);
            }
        });
        code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codeKeyPressed(evt);
            }
        });

        cap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                capKeyPressed(evt);
            }
        });

        coul.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                coulKeyPressed(evt);
            }
        });

        jLabel5.setText("Type  :");

        type.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                typeKeyPressed(evt);
            }
        });

        jButton2.setText("Modifier");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cap, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(coul, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(coul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        setSize(new java.awt.Dimension(375, 278));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String CODE = code.getText();
        String TY = type.getText();
        String CAP = cap.getText();
        String COUL = coul.getText();
               
        //la requête
        String requete="INSERT INTO appareil(CodeAPPLE,Type,Capacité,Couleur)\n"+
                "VALUES ('"+CODE+"','"+TY+"','"+CAP+"','"+COUL+"') " ;
        
        //Exécuter la requête
       try{
         stm=maConnexion.get_connexion().createStatement();
        // stm.executeQuery(requete); ne passe pas pour l'insertion dans mysql
        stm.executeUpdate(requete); 
        //java.awt.Toolkit.getDefaultToolkit().beep();
         JOptionPane.showMessageDialog(null,"Le nouveau code APPLE a été ajouté");
         code.setText("");
         type.setText(""); 
         cap.setText("");
         coul.setText("");
         code.requestFocusInWindow();
         //((JTextField)date_blv.getDateEditor().getUiComponent()).setText("");
  
       }
       catch(SQLException e){
           java.awt.Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(null,e);
                code.setText("");
                type.setText(""); 
                cap.setText("");
                coul.setText("");
                code.requestFocusInWindow();
         
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void codeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codeKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            String CODE = code.getText();
            type.setText("");
            cap.setText("");
            coul.setText("");
            String requete="Select * from appareil WHERE codeApple='"+CODE+"'" ;
            try{
                stm=maConnexion.get_connexion().createStatement();
                rs=stm.executeQuery(requete);
                while (rs.next()){
                        type.setText(rs.getString("Type"));
                        cap.setText(rs.getString("Capacité"));
                        coul.setText(rs.getString("Couleur"));
                }
            }
            catch (SQLException e) {
                
            }
            
            type.requestFocusInWindow();
            
        }
    }//GEN-LAST:event_codeKeyPressed

    private void typeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_typeKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            cap.requestFocusInWindow();
        }
    }//GEN-LAST:event_typeKeyPressed

    private void capKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_capKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            coul.requestFocusInWindow();
        }
    }//GEN-LAST:event_capKeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
           String CODE = code.getText();
        String TY = type.getText();
        String CAP = cap.getText();
        String COUL = coul.getText();
               
        //la requête
        String requete="INSERT INTO appareil(CodeAPPLE,Type,Capacité,Couleur)\n"+
                "VALUES ('"+CODE+"','"+TY+"','"+CAP+"','"+COUL+"') " ;
        
        //Exécuter la requête
       try{
         stm=maConnexion.get_connexion().createStatement();
        // stm.executeQuery(requete); ne passe pas pour l'insertion dans mysql
        stm.executeUpdate(requete); 
        //java.awt.Toolkit.getDefaultToolkit().beep();
         JOptionPane.showMessageDialog(null,"Le nouveau code APPLE a été ajouté");
         code.setText("");
         type.setText(""); 
         cap.setText("");
         coul.setText("");
         code.requestFocusInWindow();
         //((JTextField)date_blv.getDateEditor().getUiComponent()).setText("");
  
       }
            catch(SQLException e){
                java.awt.Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(null,e);
                code.setText("");
                type.setText(""); 
                cap.setText("");
                coul.setText("");
                code.requestFocusInWindow();
            }
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void coulKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_coulKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
           String CODE = code.getText();
        String TY = type.getText();
        String CAP = cap.getText();
        String COUL = coul.getText();
               
        //la requête
        String requete="INSERT INTO appareil(CodeAPPLE,Type,Capacité,Couleur)\n"+
                "VALUES ('"+CODE+"','"+TY+"','"+CAP+"','"+COUL+"') " ;
        
        //Exécuter la requête
       try{
         stm=maConnexion.get_connexion().createStatement();
        // stm.executeQuery(requete); ne passe pas pour l'insertion dans mysql
        stm.executeUpdate(requete); 
        //java.awt.Toolkit.getDefaultToolkit().beep();
         JOptionPane.showMessageDialog(null,"Le nouveau code APPLE a été ajouté");
         code.setText("");
         type.setText(""); 
         cap.setText("");
         coul.setText("");
         code.requestFocusInWindow();
         //((JTextField)date_blv.getDateEditor().getUiComponent()).setText("");
  
       }
            catch(SQLException e){
                java.awt.Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(null,e);
                //System.err.println(e);
                code.setText("");
                type.setText(""); 
                cap.setText("");
                coul.setText("");
                code.requestFocusInWindow();
            }
        }
    }//GEN-LAST:event_coulKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
           String CODE = code.getText();
        String TY = type.getText();
        String CAP = cap.getText();
        String COUL = coul.getText();
               
        //la requête
        String requete="UPDATE appareil SET Type='"+TY+"', Capacité='"+CAP+"',Couleur='"+COUL+"' WHERE CodeAPPLE='"+CODE+"'" ;
               
        //Exécuter la requête
       try{
         stm=maConnexion.get_connexion().createStatement();
        // stm.executeQuery(requete); ne passe pas pour l'insertion dans mysql
        stm.executeUpdate(requete); 
        //java.awt.Toolkit.getDefaultToolkit().beep();
         JOptionPane.showMessageDialog(null,"Le code a été modifié");
         code.setText("");
         type.setText(""); 
         cap.setText("");
         coul.setText("");
         code.requestFocusInWindow();
         //((JTextField)date_blv.getDateEditor().getUiComponent()).setText("");
  
       }
            catch(SQLException e){
                java.awt.Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(null,e);
                System.err.println(e);
                code.setText("");
                type.setText(""); 
                cap.setText("");
                coul.setText("");
                code.requestFocusInWindow();
            }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        
    }//GEN-LAST:event_jButton2KeyPressed

    private void codeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codeFocusGained
        code.selectAll();
    }//GEN-LAST:event_codeFocusGained
/*
    private void codeKeyPressed(java.awt.event.KeyEvent evt) {                                
        
    }   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAppareil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAppareil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAppareil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAppareil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAppareil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cap;
    private javax.swing.JTextField code;
    private javax.swing.JTextField coul;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField type;
    // End of variables declaration//GEN-END:variables
}
