/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package appliswap;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Teckos
 */
public class Recherche_IMEI1 extends javax.swing.JFrame {
    Statement stm;
    Statement stm1;
    connexion maConnexion;
    connexion1 maConnexion1;
    //connexion_1 maConnexion_1=new connexion_1();
    ResultSet rs;
    ResultSet rs1;
    String LOCAL="OUI";
    private String id;
    private String CHOIX;
    //String id;
    /**
     * Creates new form Recherche_IMEI
     */

    public Recherche_IMEI1() {
        initComponents();
        Text1.setDocument(new JTextFieldLimit(18));
        Text2.setEnabled(false);
        Text3.setEnabled(false);
        Text4.setEnabled(false);
        bouton_copie.setEnabled(false);
        Text1.requestFocusInWindow();
        BDD_local.doClick();
        try {
        if (LOCAL.equals("OUI")) {maConnexion1=new connexion1();
            stm=maConnexion1.get_connexion().createStatement();
            }
            else {maConnexion=new connexion();
            stm=maConnexion.get_connexion().createStatement();}
        }
        catch (SQLException e){
            System.err.println(e);
            java.awt.Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, e);
        }
        
        //operateur.setEnabled(false);
        //N_REP.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Text1 = new javax.swing.JTextField();
        Choix1 = new javax.swing.JComboBox();
        Text2 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextIMEIO = new javax.swing.JTextField();
        jTextID = new javax.swing.JTextField();
        jTextStatus = new javax.swing.JTextField();
        jTextDésignation = new javax.swing.JTextField();
        jTextEtat = new javax.swing.JTextField();
        jTextNRep = new javax.swing.JTextField();
        jTextIMEIN = new javax.swing.JTextField();
        jTextPrix = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextBL = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextCodeA = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextNBL = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextOpé = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextUPS = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Text3 = new javax.swing.JTextField();
        Text4 = new javax.swing.JTextField();
        bouton_copie = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        BDD_local = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GESTION DES REPARATIONS APPLE");

        Text1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Text1FocusGained(evt);
            }
        });
        Text1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Text1MouseClicked(evt);
            }
        });
        Text1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text1ActionPerformed(evt);
            }
        });
        Text1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Text1KeyPressed(evt);
            }
        });

        Choix1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Recherche IMEI", "-MàJ n° réparation", "Recherche n° rép", "-MàJ IMEI remplacé" }));
        Choix1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Choix1ActionPerformed(evt);
            }
        });

        Text2.setToolTipText("Numéro de réparation ou nouvel IMEI");
        Text2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Text2MouseDragged(evt);
            }
        });
        Text2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Text2FocusGained(evt);
            }
        });
        Text2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Text2MouseClicked(evt);
            }
        });
        Text2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text2ActionPerformed(evt);
            }
        });
        Text2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Text2KeyPressed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jTable1ComponentResized(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 955, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Aperçu", jPanel1);

        jLabel1.setText("ID");

        jLabel2.setText("IMEI/N° de série Original");

        jLabel3.setText("Status demande");

        jLabel4.setText("Désignation");

        jLabel5.setText("N° de réparation");

        jLabel6.setText("Etat swap");

        jLabel7.setText("Nouvel IMEI");

        jLabel8.setText("Prix réparation");

        jTextStatus.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextStatusFocusGained(evt);
            }
        });
        jTextStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextStatusActionPerformed(evt);
            }
        });
        jTextStatus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextStatusKeyPressed(evt);
            }
        });

        jTextDésignation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextDésignationKeyPressed(evt);
            }
        });

        jTextEtat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextEtatFocusGained(evt);
            }
        });
        jTextEtat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEtatActionPerformed(evt);
            }
        });
        jTextEtat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextEtatKeyPressed(evt);
            }
        });

        jTextNRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNRepActionPerformed(evt);
            }
        });

        jTextPrix.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextPrixFocusGained(evt);
            }
        });
        jTextPrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPrixActionPerformed(evt);
            }
        });
        jTextPrix.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextPrixKeyPressed(evt);
            }
        });

        jLabel9.setText("N° BL SPB");

        jButton1.setText("Mettre à jour");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextCodeA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCodeAActionPerformed(evt);
            }
        });
        jTextCodeA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextCodeAKeyPressed(evt);
            }
        });

        jLabel10.setText("Code Apple");

        jTextNBL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNBLActionPerformed(evt);
            }
        });

        jLabel11.setText("Bon de Livraison");

        jTextOpé.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextOpéActionPerformed(evt);
            }
        });
        jTextOpé.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextOpéKeyPressed(evt);
            }
        });

        jLabel12.setText("Opérateur");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jTable2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jTable2ComponentResized(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTable2ComponentShown(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jTextUPS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextUPSFocusGained(evt);
            }
        });
        jTextUPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextUPSActionPerformed(evt);
            }
        });
        jTextUPS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextUPSKeyPressed(evt);
            }
        });

        jLabel14.setText("UPS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jTextID, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextIMEIO, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextBL, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(421, 421, 421))
                                    .addComponent(jTextDésignation)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                    .addComponent(jTextNRep))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextUPS, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextEtat)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jTextIMEIN, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextCodeA, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextOpé, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextPrix)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 8, Short.MAX_VALUE))
                                    .addComponent(jTextNBL))))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextIMEIO)
                            .addComponent(jTextID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel9)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextBL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextDésignation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(2, 2, 2)
                        .addComponent(jTextEtat))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(2, 2, 2)
                        .addComponent(jTextNBL))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(2, 2, 2)
                        .addComponent(jTextPrix))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(2, 2, 2)
                        .addComponent(jTextOpé))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(2, 2, 2)
                        .addComponent(jTextNRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(2, 2, 2)
                        .addComponent(jTextUPS))
                    .addComponent(jLabel10)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jTextCodeA))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(2, 2, 2)
                        .addComponent(jTextIMEIN)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Avancé", jPanel2);

        Text3.setToolTipText("Code APPLE");
        Text3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Text3FocusGained(evt);
            }
        });
        Text3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text3ActionPerformed(evt);
            }
        });
        Text3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Text3KeyPressed(evt);
            }
        });

        Text4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text4ActionPerformed(evt);
            }
        });

        bouton_copie.setToolTipText("Copie IMEI/N° série d'origine");
        bouton_copie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_copieActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabel13.setText("V. 4.3.1");

        BDD_local.setText("BDD locale");
        BDD_local.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BDD_localMouseClicked(evt);
            }
        });
        BDD_local.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDD_localActionPerformed(evt);
            }
        });

        jMenu1.setText("Swaps");

        jMenuItem2.setText("Listes SWAPS");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setText("Codes APPLE");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("SWAP ENGINE");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem7.setText("Tracking UPS");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Bons de livraison");

        jMenuItem4.setText("Saisie appareils");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Modification");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Gestion BL");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Text1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Choix1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BDD_local)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Text2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bouton_copie, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Text3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Text4, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Choix1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BDD_local)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bouton_copie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Text2)
                        .addComponent(Text3)
                        .addComponent(Text4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    void advancedIMEI(){
        String TEXT1 = Text1.getText();
        String id_="";
        
        jTextID.setEnabled(false);
        jTextID.setText("");
        jTextIMEIO.setText("");
        jTextStatus.setText("");
        jTextDésignation.setText("");
        jTextNRep.setText("");
        jTextIMEIN.setText("");
        jTextPrix.setText("");
        jTextBL.setText("");
        jTextEtat.setText("");
        jTextCodeA.setText("");
        jTextNBL.setText("");
        jTextOpé.setText("");
        jTextUPS.setText("");
        String requete ="Select * from liste_swap where IMEI_ORI='"+TEXT1+"'";
        
        try {
            if (LOCAL.equals("OUI")) {stm=maConnexion1.get_connexion().createStatement();}
            else {stm=maConnexion.get_connexion().createStatement();}
            //stm=maConnexion.get_connexion().createStatement();
            rs=stm.executeQuery(requete);
            while(rs.next()){
                jTextID.setText(rs.getString("ID"));
                jTextIMEIO.setText(rs.getString("IMEI_ORI"));
                jTextStatus.setText(rs.getString("Status"));
                jTextDésignation.setText(rs.getString("DES"));
                jTextBL.setText(rs.getString("BL_SPB"));
                id_=rs.getString("ID");
            }
            String requete1="Select * from réparation where ID='"+id_+"'";
            rs1=stm.executeQuery(requete1);
            while(rs1.next()){
                jTextNRep.setText(rs1.getString("N_REP"));
                jTextIMEIN.setText(rs1.getString("IMEI_NEW"));
                jTextPrix.setText(rs1.getString("Prix"));
                jTextEtat.setText(rs1.getString("Etat"));
                jTextCodeA.setText(rs1.getString("CodeAPPLE"));
                jTextNBL.setText(rs1.getString("N_BL"));
                jTextOpé.setText(rs1.getString("Opérateur"));
                jTextUPS.setText(rs1.getString("UPS"));
                
            }
                       
        }
        catch(SQLException e){
            System.err.println(e);
            java.awt.Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, e);
        }
        
        
    }
    
    void advancedNrep(){
        String TEXT1 = Text1.getText();
        String id_="";
        
        jTextID.setEnabled(false);
        jTextID.setText("");
        jTextIMEIO.setText("");
        jTextStatus.setText("");
        jTextDésignation.setText("");
        jTextNRep.setText("");
        jTextIMEIN.setText("");
        jTextPrix.setText("");
        jTextBL.setText("");
        jTextEtat.setText("");
        jTextCodeA.setText("");
        jTextNBL.setText("");
        jTextOpé.setText("");
        jTextUPS.setText("");
        
        String requete ="Select * from réparation where N_REP like '%"+TEXT1+"%'";
        try {
            if (LOCAL.equals("OUI")) {stm=maConnexion1.get_connexion().createStatement();}
            else {stm=maConnexion.get_connexion().createStatement();}
            
            //stm=maConnexion.get_connexion().createStatement();
            rs=stm.executeQuery(requete);
            while(rs.next()){
                jTextNRep.setText(rs.getString("N_REP"));
                jTextIMEIN.setText(rs.getString("IMEI_NEW"));
                jTextPrix.setText(rs.getString("Prix"));
                jTextEtat.setText(rs.getString("Etat"));
                jTextCodeA.setText(rs.getString("CodeAPPLE"));
                jTextNBL.setText(rs.getString("N_BL"));
                jTextOpé.setText(rs.getString("Opérateur"));
                jTextUPS.setText(rs.getString("UPS"));
                id_=rs.getString("ID");
                
            }
            String requete1="Select * from liste_swap where ID='"+id_+"'";
            rs1=stm.executeQuery(requete1);
            while(rs1.next()){
                if (rs1.getString("BL_SPB").startsWith("BOUYGUES"))  {
                                Text4.setText("!!! Attention, contrat Bouygues !!!");
                                java.awt.Toolkit.getDefaultToolkit().beep();
                            }
                if (rs1.getString("BL_SPB").startsWith("!!RETOUR"))  {
                                java.awt.Toolkit.getDefaultToolkit().beep();
                                Text4.setText("!!! Attention, SAV !!!");
                                java.awt.Toolkit.getDefaultToolkit().beep();
                                
                            }
                jTextID.setText(rs1.getString("ID"));
                jTextIMEIO.setText(rs1.getString("IMEI_ORI"));
                jTextStatus.setText(rs1.getString("Status"));
                jTextDésignation.setText(rs1.getString("DES"));
                jTextBL.setText(rs1.getString("BL_SPB"));
            }
                       
        }
        catch(SQLException e){
            System.err.println(e);
            java.awt.Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, e);
        }
        
        
    }
    
        void advancedUPS(){
        String TEXT1 = Text1.getText();
        String id_="";
        
        jTextID.setEnabled(false);
        jTextID.setText("");
        jTextIMEIO.setText("");
        jTextStatus.setText("");
        jTextDésignation.setText("");
        jTextNRep.setText("");
        jTextIMEIN.setText("");
        jTextPrix.setText("");
        jTextBL.setText("");
        jTextEtat.setText("");
        jTextCodeA.setText("");
        jTextNBL.setText("");
        jTextOpé.setText("");
        jTextUPS.setText("");
        
        String requete ="Select * from réparation where UPS like '%"+TEXT1+"%'";
        try {
            if (LOCAL.equals("OUI")) {stm=maConnexion1.get_connexion().createStatement();}
            else {stm=maConnexion.get_connexion().createStatement();}
            
            //stm=maConnexion.get_connexion().createStatement();
            rs=stm.executeQuery(requete);
            while(rs.next()){
                jTextNRep.setText(rs.getString("N_REP"));
                jTextIMEIN.setText(rs.getString("IMEI_NEW"));
                jTextPrix.setText(rs.getString("Prix"));
                jTextEtat.setText(rs.getString("Etat"));
                jTextCodeA.setText(rs.getString("CodeAPPLE"));
                jTextNBL.setText(rs.getString("N_BL"));
                jTextOpé.setText(rs.getString("Opérateur"));
                jTextUPS.setText(rs.getString("UPS"));
                id_=rs.getString("ID");
                
            }
            String requete1="Select * from liste_swap where ID='"+id_+"'";
            rs1=stm.executeQuery(requete1);
            while(rs1.next()){
                if (rs1.getString("BL_SPB").startsWith("BOUYGUES"))  {
                                Text4.setText("!!! Attention, contrat Bouygues !!!");
                                java.awt.Toolkit.getDefaultToolkit().beep();
                            }
                if (rs1.getString("BL_SPB").startsWith("!!RETOUR"))  {
                                java.awt.Toolkit.getDefaultToolkit().beep();
                                Text4.setText("!!! Attention, SAV !!!");
                                java.awt.Toolkit.getDefaultToolkit().beep();
                                
                            }
                jTextID.setText(rs1.getString("ID"));
                jTextIMEIO.setText(rs1.getString("IMEI_ORI"));
                jTextStatus.setText(rs1.getString("Status"));
                jTextDésignation.setText(rs1.getString("DES"));
                jTextBL.setText(rs1.getString("BL_SPB"));
            }
                       
        }
        catch(SQLException e){
            System.err.println(e);
            java.awt.Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, e);
        }
        
        
    }
    
    private void Text1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Text1KeyPressed
                
                
                //if(evt.getKeyCode()==KeyEvent.VK_ENTER){
                //    Text1.requestFocusInWindow();
                //}
    }//GEN-LAST:event_Text1KeyPressed

    private void Choix1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Choix1ActionPerformed
          if (Choix1.getSelectedItem().equals("-MàJ n° réparation"))
          {
            Text3.setEnabled(false);
            Text2.setEnabled(true);
            Text2.setText("");
            Text1.requestFocusInWindow();
            CHOIX="-MàJ n° réparation";
          }
          else if (Choix1.getSelectedItem().equals("-MàJ IMEI remplacé"))
          {
            Text3.setEnabled(true);
            Text2.setEnabled(true);
            bouton_copie.setEnabled(true);
            Text2.setText("");
            Text1.requestFocusInWindow();
            CHOIX="-MàJ IMEI remplacé";
          }
          else if (Choix1.getSelectedItem().equals("Recherche n° rép"))
          {
            Text3.setEnabled(false);
            Text2.setEnabled(false);
            Text2.setText("");
            Text1.requestFocusInWindow();
            CHOIX="Recherche n° rép";
          }
          else if (Choix1.getSelectedItem().equals("Recherche IMEI")) 
          {
            Text3.setEnabled(false);
            Text2.setEnabled(false);
            Text2.setText("");
            Text1.requestFocusInWindow();
            CHOIX="Recherche IMEI";
          }
          
          
    }//GEN-LAST:event_Choix1ActionPerformed

    private void Text2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text2ActionPerformed

    private void jTable1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable1ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1ComponentResized

    private void Text2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Text2KeyPressed
         Integer taille=0;
         Integer taille1=0;
         
        String champs="";
            if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            String TEXT1 = Text1.getText();
            String TEXT2 = Text2.getText();
            String requete;
            String requete0;
            String requete1;
            
          if ((Choix1.getSelectedItem().equals("Recherche IMEI"))|(Choix1.getSelectedItem().equals("-MàJ n° réparation"))) 
          {
          taille=10;
          taille1=10;
          
          champs="N_REP";
          }
          else if ((Choix1.getSelectedItem().equals("Recherche n° rép"))|(Choix1.getSelectedItem().equals("-MàJ IMEI remplacé")))
          {
          taille=15;
          taille1=12; 
          
          champs="IMEI"; 
          }
          
            if((TEXT2.length() != taille) & (TEXT2.length() != taille1) & (TEXT2.length() != 17) )
            
                        {
                            JOptionPane.showMessageDialog(null,"Le champs "+champs+" doit avoir "+taille+" ou "+taille1+" caractères");
                            Text2.setText("");
                            Text2.requestFocusInWindow();
                        }
                
            else {
            
                        if (Choix1.getSelectedItem().equals("-MàJ n° réparation"))
                      {
 /*****/                         int row = jTable2.getSelectedRow();
 System.out.println(row);
                                  if (row==-1) {}
                                  else {
 /*****/          id = (jTable2.getModel().getValueAt(row, 0).toString());}
                                  System.out.println(id);
                        requete="INSERT INTO réparation (N_REP, ID,IMEI_NEW, Opérateur) VALUES ('"+TEXT2+"','"+id+"','"+id+"','')";
                        requete0="select A.ID, A.IMEI_ORI, A.BL_SPB, A.DES, B.N_REP, B.IMEI_NEW from liste_swap A,réparation B where (A.ID = B.ID) AND (A.IMEI_ORI = '" + TEXT1+ "')";
                        requete1="UPDATE liste_swap SET Status='Oui' WHERE IMEI_ORI='"+TEXT1+"'";

                        try {
                            if (LOCAL.equals("OUI")) {stm=maConnexion1.get_connexion().createStatement();}
                            else {stm=maConnexion.get_connexion().createStatement();}
                            
                            //stm=maConnexion.get_connexion().createStatement();
                            stm.executeUpdate(requete);
                            stm.executeUpdate(requete1);
                            rs=stm.executeQuery(requete0); 
                            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                            
                            rs=stm.executeQuery(requete0); 
                            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
                            advancedIMEI();
                            }
                        catch(SQLException e){
                                        System.err.println(e);
                                        java.awt.Toolkit.getDefaultToolkit().beep();
                                        JOptionPane.showMessageDialog(null, e);
                                    }
                         Text1.setText("");
                         Text2.setText("");
                            Text3.setText("");
                            Text4.setText("");
                            Text1.requestFocusInWindow();
                      }
                      else if (Choix1.getSelectedItem().equals("-MàJ IMEI remplacé"))
                      {
                          if ((TEXT2.length() == 17)&(TEXT2.startsWith("A"))&(TEXT2.endsWith("B")))
                          {
                              TEXT2=TEXT2.substring(1, 16);
                              Text2.setText(TEXT2);
                          }
                              
                          Text3.requestFocusInWindow();
                          Text3.selectAll();
                          
                      }
            
            }
        }
    }//GEN-LAST:event_Text2KeyPressed

    private void Text1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Text1MouseClicked
        Text1.setText("");
        Text2.setText("");
        Text3.setText("");
        Text4.setText("");
        
    }//GEN-LAST:event_Text1MouseClicked

    private void Text1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text1ActionPerformed
        Integer taille=0;
        String champs="";
        String champs2="";
        String champs3="";
        String requete="";
        String requete1="";
        Text4.setText("");
        
        String TEXT1 = Text1.getText();
        if ((Choix1.getSelectedItem().equals("Recherche IMEI"))|(Choix1.getSelectedItem().equals("-MàJ n° réparation")))
          {
          taille=15;
          champs="IMEI";
          champs2="N_REP";
          
          requete1="select B.N_REP, B.CodeAPPLE from liste_swap A,réparation B where (A.ID = B.ID) AND (A.IMEI_ORI LIKE '%" + TEXT1+ "%')";  
          requete="select ID, IMEI_ORI, BL_SPB, DES from liste_swap where IMEI_ORI = '" + TEXT1+"'";
          }
          
          else if ((Choix1.getSelectedItem().equals("Recherche n° rép")))
          {
          taille=10;
          champs="N_REP"; 
          champs2="IMEI_NEW";
          requete="select A.ID, A.IMEI_ORI, A.BL_SPB, A.DES, B.N_REP, B.IMEI_NEW from liste_swap A,réparation B where (A.ID = B.ID) AND (B.N_REP LIKE '%" + TEXT1+ "%')";
          requete1="select IMEI_NEW, CodeAPPLE from réparation WHERE N_REP='"+TEXT1+"'";
          
          }
          else if ((Choix1.getSelectedItem().equals("-MàJ IMEI remplacé")))
          {
          taille=18;
          champs="UPS"; 
          champs2="IMEI_NEW";
          requete="select A.ID, A.IMEI_ORI, A.BL_SPB, A.DES, B.N_REP, B.IMEI_NEW from liste_swap A,réparation B where (A.ID = B.ID) AND (B.UPS LIKE '%" + TEXT1+ "%')";
          requete1="select IMEI_NEW, CodeAPPLE, N_REP from réparation WHERE UPS='"+TEXT1+"'";
          
          }
                        try{
                            
                            if (LOCAL.equals("OUI")) {stm=maConnexion1.get_connexion().createStatement();}
                            else {stm=maConnexion.get_connexion().createStatement();}
                            
                            //stm=maConnexion.get_connexion().createStatement();
                            rs=stm.executeQuery(requete); 
                            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                            
                            rs=stm.executeQuery(requete); 
                            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
                            
                            id = (jTable1.getModel().getValueAt(0, 0).toString());
                            
            /*                if (LOCAL.equals("OUI")) {connexion1 maConnexion1=new connexion1();
            stm=maConnexion1.get_connexion().createStatement();
            }
            else {connexion maConnexion=new connexion();
            stm=maConnexion.get_connexion().createStatement();}*/
                            
                            //stm=maConnexion.get_connexion().createStatement();
                            rs=stm.executeQuery(requete1);
                            //NRep.setEnabled(true);
                            
                            while(rs.next()){
                                Text2.setText("");
                                Text3.setText("");
                                Text4.setText("");
                                Text2.setText(rs.getString(champs2));
                                Text3.setText(rs.getString("CodeAPPLE"));
                            }
                            
                            
                            if (Choix1.getSelectedItem().equals("-MàJ n° réparation" ))
                                {
                                advancedIMEI();
                                Text2.requestFocusInWindow();

                            }
                            else if (Choix1.getSelectedItem().equals("-MàJ IMEI remplacé" ))
                            {
                                advancedUPS();
                                //advancedNrep(); 
                                //Text2.setText("");
                                //Text3.setText("");
                                Text2.requestFocusInWindow();        
                            }
                            else if (Choix1.getSelectedItem().equals("Recherche IMEI" ))
                            {
                                
                                advancedIMEI();
                                Text1.setText("");
                                Text2.setText("");
                                Text3.setText("");
                                Text4.setText("");
                                
                                Text1.requestFocusInWindow();
                                
                            }
                            else if (Choix1.getSelectedItem().equals("Recherche n° rép" ))
                            {
                                advancedNrep();
                                Text1.setText("");
                                Text2.setText("");
                                Text3.setText("");
                                Text4.setText("");
  
                                Text1.requestFocusInWindow();
                            }
                            /*stm=maConnexion.get_connexion().createStatement();
                            rs=stm.executeQuery(requete); 
                            
                            jTable1.setModel(DbUtils.resultSetToTableModel(rs));*/
                        }
                        catch(SQLException e){
                            System.err.println(e);
                            java.awt.Toolkit.getDefaultToolkit().beep();
                            JOptionPane.showMessageDialog(null, e);
                        }
                    //}
    }//GEN-LAST:event_Text1ActionPerformed

    private void Text1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Text1FocusGained
        Text1.setText("");
        Text2.setText("");
        Text3.setText("");
        Text4.setText("");
    }//GEN-LAST:event_Text1FocusGained

    private void Text2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Text2FocusGained
       Text2.selectAll();
    }//GEN-LAST:event_Text2FocusGained

    private void jTextNRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNRepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNRepActionPerformed

    private void jTextEtatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEtatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEtatActionPerformed
    void boutonMAJ () {
        String id_ = jTextID.getText();
        String imeio=jTextIMEIO.getText();
        String status=jTextStatus.getText();
        String des =jTextDésignation.getText();
        String nrep = jTextNRep.getText();
        String Imein = jTextIMEIN.getText();
        String prix = jTextPrix.getText();
        String bl = jTextBL.getText();
        String etat = jTextEtat.getText();
        String codeA = jTextCodeA.getText();
        String nbl = jTextNBL.getText();
        String ope = jTextOpé.getText();
        String ups = jTextUPS.getText();
        
        
        String requete="UPDATE liste_swap A set A.IMEI_ORI='"+imeio+"',A.Status = '"+status+"', A.DES ='"+des+"', A.BL_SPB='"+bl+"' where (A.ID = '"+id_+"')" ;
        String requete1="UPDATE réparation B set B.N_REP ='"+nrep+"', B.IMEI_NEW ='"+Imein+"', B.Prix ='"+prix+"', B.Etat ='"+etat+"', B.CodeAPPLE ='"+codeA+
                "', B.N_BL ='"+nbl+"', B.Opérateur ='"+ope+"', B.UPS='"+ups+"' where (B.ID='"+id_+"')" ;
                try {
            if (LOCAL.equals("OUI")) {stm=maConnexion1.get_connexion().createStatement();
            }
            else {stm=maConnexion.get_connexion().createStatement();}
            
            //stm=maConnexion.get_connexion().createStatement();
            stm.executeUpdate(requete);
            stm.executeUpdate(requete1);
                                  
        }
        catch(SQLException e){
            System.err.println(e);
            java.awt.Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, e);
        }
        Text1.setText("");
        Text2.setText("");
        Text3.setText("");
        Text4.setText("");
        jTextID.setText("");
        jTextIMEIO.setText("");
        jTextStatus.setText("");
        jTextDésignation.setText("");
        jTextNRep.setText("");
        jTextIMEIN.setText("");
        jTextPrix.setText("");
        jTextBL.setText("");
        jTextEtat.setText("");
        jTextCodeA.setText("");
        jTextNBL.setText("");
        jTextOpé.setText("");
        jTextUPS.setText("");
        Text1.requestFocusInWindow();
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        boutonMAJ();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextNBLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNBLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNBLActionPerformed

    private void jTextOpéActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextOpéActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextOpéActionPerformed

    private void jTable2ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable2ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2ComponentResized

    private void Text3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Text3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Text3FocusGained

    private void Text3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text3ActionPerformed

    private void Text3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Text3KeyPressed
       Integer taille=0;
        String champs="";
        String TEXT1 = Text1.getText();
            String TEXT2 = Text2.getText();
            String TEXT3 = Text3.getText();
            if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            
            String requete;
            String requete0;
            String requete1;
            String temp;
            String temp1;
            
          
                      if ((Choix1.getSelectedItem().equals("-MàJ IMEI remplacé")) & (TEXT1 != ""))
                      {
                        if (TEXT3.equals("REP-REFUS")) {
                        temp ="ETAT='Refusé'";
                        //temp1="";
                        }
                        else if ((TEXT3.equals("REP-IPHONE")) || (TEXT3.equals("REP-IPHONE6"))) {
                        temp ="ETAT='Réparé'";
                        }
                             else   {
                            temp="ETAT='Oui'";
                            //temp1=", Opérateur=''";
                        }
                        requete="UPDATE réparation SET IMEI_NEW='"+TEXT2+"',"+temp+", CodeAPPLE='"+TEXT3+"' WHERE UPS='"+TEXT1+"'"; 
                        requete0="select A.ID, A.IMEI_ORI, A.BL_SPB, A.DES, B.N_REP, B.IMEI_NEW from liste_swap A,réparation B where (A.ID = B.ID) AND (B.UPS = '" + TEXT1+ "')";
                         try {
                            if (LOCAL.equals("OUI")) {stm=maConnexion1.get_connexion().createStatement();}
                         else {stm=maConnexion.get_connexion().createStatement();}
                            
                            //stm=maConnexion.get_connexion().createStatement();
                            stm.executeUpdate(requete);
                            rs=stm.executeQuery(requete0);
                            /*if (rs.getString("BL_SPB").startsWith("Bouygues"))  {
                                JOptionPane.showMessageDialog(null, "Attention, contrat Bouygues");
                            }
                            if (rs.getString("BL_SPB").startsWith("Esp"))  {
                                JOptionPane.showMessageDialog(null, "Attention, contrat Espagne");
                            }*/
                            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                            rs=stm.executeQuery(requete0);
                            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
                            advancedNrep();
                            Text1.setText("");
            Text2.setText("");
            Text3.setText("");
            Text4.setText("");
            Text1.requestFocusInWindow();
                            }
                        catch(SQLException e){
                                        System.err.println(e);
                                        java.awt.Toolkit.getDefaultToolkit().beep();
                                        JOptionPane.showMessageDialog(null, e);
                                        //Text1.setText("");
           
            Text3.setText("");
            Text4.setText("");
            Text3.requestFocusInWindow();
                                    }
                      
            
            

           
            
            }
        }
    }//GEN-LAST:event_Text3KeyPressed

    private void jTable2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable2ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2ComponentShown

    private void Text2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Text2MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_Text2MouseDragged

    private void Text4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text4ActionPerformed

    private void jTextStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextStatusActionPerformed

    private void jTextStatusFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextStatusFocusGained
        jTextStatus.setText("");
    }//GEN-LAST:event_jTextStatusFocusGained

    private void jTextStatusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextStatusKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            boutonMAJ();
        }
    }//GEN-LAST:event_jTextStatusKeyPressed

    private void jTextEtatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextEtatFocusGained
        jTextEtat.setText("");
    }//GEN-LAST:event_jTextEtatFocusGained

    private void jTextEtatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextEtatKeyPressed
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            boutonMAJ();
        }
    }//GEN-LAST:event_jTextEtatKeyPressed

    private void Text2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Text2MouseClicked
        Text2.setText("");
    }//GEN-LAST:event_Text2MouseClicked

    private void jTextPrixFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextPrixFocusGained
        jTextPrix.setText("");
    }//GEN-LAST:event_jTextPrixFocusGained

    private void jTextPrixKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPrixKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            boutonMAJ();
    }//GEN-LAST:event_jTextPrixKeyPressed
    }
    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
                     
           int row = jTable2.getSelectedRow();
           String t = (jTable2.getModel().getValueAt(row, 0).toString());
           
          String TEXT1 = Text1.getText();
        String id_="";
        
        jTextID.setEnabled(false);
        jTextID.setText("");
        jTextIMEIO.setText("");
        jTextStatus.setText("");
        jTextDésignation.setText("");
        jTextNRep.setText("");
        jTextIMEIN.setText("");
        jTextPrix.setText("");
        jTextBL.setText("");
        jTextEtat.setText("");
        jTextCodeA.setText("");
        jTextNBL.setText("");
        jTextOpé.setText("");
        jTextUPS.setText("");
        
        String requete ="Select * from liste_swap where ID='"+t+"'";
        
        try {
            if (LOCAL.equals("OUI")) {stm=maConnexion1.get_connexion().createStatement();}
            else {stm=maConnexion.get_connexion().createStatement();}
            //stm=maConnexion.get_connexion().createStatement();
            rs=stm.executeQuery(requete);
            while(rs.next()){
                jTextID.setText(rs.getString("ID"));
                jTextIMEIO.setText(rs.getString("IMEI_ORI"));
                jTextStatus.setText(rs.getString("Status"));
                jTextDésignation.setText(rs.getString("DES"));
                jTextBL.setText(rs.getString("BL_SPB"));
                id_=rs.getString("ID");
            }
            String requete1="Select * from réparation where ID='"+t+"'";
            //stm=maConnexion.get_connexion().createStatement();
            rs1=stm.executeQuery(requete1);
            while(rs1.next()){
                jTextNRep.setText(rs1.getString("N_REP"));
                jTextIMEIN.setText(rs1.getString("IMEI_NEW"));
                jTextPrix.setText(rs1.getString("Prix"));
                jTextEtat.setText(rs1.getString("Etat"));
                jTextCodeA.setText(rs1.getString("CodeAPPLE"));
                jTextNBL.setText(rs1.getString("N_BL"));
                jTextOpé.setText(rs1.getString("Opérateur"));
                jTextUPS.setText(rs1.getString("UPS"));
                
            }       
        }
        catch(SQLException e){
            System.err.println(e);
            java.awt.Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, e);
        }
        /*try {
            
            
            if (LOCAL.equals("OUI")) {connexion1 maConnexion1=new connexion1();
            stm=maConnexion1.get_connexion().createStatement();
            }
            else {connexion maConnexion=new connexion();
            stm=maConnexion.get_connexion().createStatement();}
            String requete1="Select * from réparation where ID='"+t+"'";
            //stm=maConnexion.get_connexion().createStatement();
            rs1=stm.executeQuery(requete1);
            while(rs1.next()){
                jTextNRep.setText(rs1.getString("N_REP"));
                jTextIMEIN.setText(rs1.getString("IMEI_NEW"));
                jTextPrix.setText(rs1.getString("Prix"));
                jTextEtat.setText(rs1.getString("Etat"));
                jTextCodeA.setText(rs1.getString("CodeAPPLE"));
                jTextNBL.setText(rs1.getString("N_BL"));
                jTextOpé.setText(rs1.getString("Opérateur"));
                
            }
        }
        catch(SQLException e){
            System.err.println(e);
            java.awt.Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, e);
        }*/
         
         
         
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTextCodeAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCodeAKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            boutonMAJ();}
    }//GEN-LAST:event_jTextCodeAKeyPressed

    private void jTextPrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPrixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPrixActionPerformed

    private void jTextOpéKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextOpéKeyPressed
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            boutonMAJ();
    }                           
    }//GEN-LAST:event_jTextOpéKeyPressed

    private void bouton_copieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_copieActionPerformed
        Text2.setText(jTextIMEIO.getText());
        Text3.requestFocusInWindow();
        Text3.selectAll();
    }//GEN-LAST:event_bouton_copieActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
              AffichageBL f= new AffichageBL();
        f.setVisible(true); 
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
              JFrameAppareil f= new JFrameAppareil();
        f.setVisible(true); 
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
               JFrameSaisie f= new JFrameSaisie();
        f.setVisible(true); 
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
               JFrameModification f= new JFrameModification();
        f.setVisible(true); 
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
               JFrameBonLivraison f= new JFrameBonLivraison();
        f.setVisible(true); 
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jTextCodeAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCodeAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCodeAActionPerformed

    private void jTextDésignationKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextDésignationKeyPressed
                 if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            boutonMAJ();
        }
    }//GEN-LAST:event_jTextDésignationKeyPressed

    private void BDD_localMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BDD_localMouseClicked
        try {
        if(BDD_local.isSelected()==true)
            {LOCAL="OUI";
            maConnexion1=new connexion1();
            stm=maConnexion1.get_connexion().createStatement();}
        else {LOCAL="NON";
            maConnexion=new connexion();
            stm=maConnexion.get_connexion().createStatement();}
        System.out.println("Local : "+ LOCAL);
        }
        catch (SQLException e){
            System.err.println(e);
            java.awt.Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, "Erreur de connexion à la BDD");
        }
        
       
    }//GEN-LAST:event_BDD_localMouseClicked

    private void BDD_localActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDD_localActionPerformed

    }//GEN-LAST:event_BDD_localActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Swap_ENGINE f= new Swap_ENGINE();
        f.setVisible(true); 
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        Tracking_UPS f= new Tracking_UPS();
        f.setVisible(true); 
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jTextUPSFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextUPSFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUPSFocusGained

    private void jTextUPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextUPSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUPSActionPerformed

    private void jTextUPSKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextUPSKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUPSKeyPressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recherche_IMEI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recherche_IMEI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recherche_IMEI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recherche_IMEI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recherche_IMEI1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BDD_local;
    private javax.swing.JComboBox Choix1;
    private javax.swing.JTextField Text1;
    private javax.swing.JTextField Text2;
    private javax.swing.JTextField Text3;
    private javax.swing.JTextField Text4;
    private javax.swing.JButton bouton_copie;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextBL;
    private javax.swing.JTextField jTextCodeA;
    private javax.swing.JTextField jTextDésignation;
    private javax.swing.JTextField jTextEtat;
    private javax.swing.JTextField jTextID;
    private javax.swing.JTextField jTextIMEIN;
    private javax.swing.JTextField jTextIMEIO;
    private javax.swing.JTextField jTextNBL;
    private javax.swing.JTextField jTextNRep;
    private javax.swing.JTextField jTextOpé;
    private javax.swing.JTextField jTextPrix;
    private javax.swing.JTextField jTextStatus;
    private javax.swing.JTextField jTextUPS;
    // End of variables declaration//GEN-END:variables
}
