/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package appliswap;


import javax.swing.ImageIcon;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import org.openqa.selenium.By;
import org.openqa.selenium.TimeoutException;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

/**
 *
 * @author Teckos
 */
public class Tracking_UPS extends javax.swing.JFrame {

    WebDriver driver;
    WebDriverWait wait;
    WebDriverWait wait0;
    ImageIcon loader =  new ImageIcon("C:\\appliSWAP2\\src\\appliswap\\loader.gif");
    ImageIcon ok =  new ImageIcon("C:\\appliSWAP2\\src\\appliswap\\ok-small.gif");
    Statement stm;
    connexion maConnexion;
    ResultSet rs;
    
    public Tracking_UPS() {
        initComponents();
        maConnexion=new connexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bouton_Browser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        trackings = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        lab = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Bouton_Browser.setText("Browser");
        Bouton_Browser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_BrowserActionPerformed(evt);
            }
        });

        trackings.setColumns(20);
        trackings.setRows(5);
        jScrollPane1.setViewportView(trackings);

        jButton1.setText("Check");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lab.setAlignmentY(0.0F);
        lab.setAutoscrolls(true);
        lab.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lab.setOpaque(true);
        lab.setRequestFocusEnabled(false);
        lab.setVerifyInputWhenFocusTarget(false);

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Bouton_Browser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(lab, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Bouton_Browser)
                        .addComponent(jButton1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton2)
                        .addComponent(lab, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bouton_BrowserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_BrowserActionPerformed

        driver = new FirefoxDriver();
        Integer attente=60;
        driver.get("https://webmail.gandi.net/?_task=mail");
        wait = (new WebDriverWait(driver, attente));
        wait0 = (new WebDriverWait(driver, 0));
        driver.findElement(By.id("rcmloginuser")).sendKeys("contact@3rsolutions.fr");
        driver.findElement(By.id("rcmloginpwd")).sendKeys("az34(-è_");
        driver.findElement(By.cssSelector("input.button.mainaction")).click();
        

       
    }//GEN-LAST:event_Bouton_BrowserActionPerformed

    private void boucle(){
        Integer i=0;
        String etat="loading";
        System.out.println("Début boucle");
        while (etat.equals("loading")) {
                try {wait0.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("#div.loading")));
                
                    etat="loading";
                    i++;
                    System.out.println("Boucle :"+i);
                }
                catch (TimeoutException e2){
                    etat="ok";
                }
        }
        
        
    }
    
    private String verif(String track){
        String result="Erreur";
        driver.findElement(By.cssSelector("#quicksearchbox")).clear();
        driver.findElement(By.cssSelector("#quicksearchbox")).sendKeys(track+"\n");
        driver.findElement(By.cssSelector("#quicksearchbox")).submit();
        //div.loading:nth-child(2)
        //div.confirmation:nth-child(7)
        
        //boucle();
        
        try {
                Thread.sleep(2000);}
                catch (InterruptedException e) {
                }
        try{
         wait.until(ExpectedConditions.elementToBeClickable(By.linkText("Votre produit de remplacement a été expédié")));
                try {
                Thread.sleep(1800);}
                catch (InterruptedException e) {
                }
        driver.findElement(By.linkText("Votre produit de remplacement a été expédié")).click();
        driver.findElement(By.linkText("Votre produit de remplacement a été expédié")).click();
        //driver.switchTo().window("iframe");
        wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".content > table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(2) > td:nth-child(1) > table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(1) > table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(1)")));
        
        String tracking = driver.findElement(By.cssSelector(".content > table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(2) > td:nth-child(1) > table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(1) > table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(1)")).getText();
        
        String nrep []= tracking.split("\n");
        /*System.out.println(nrep[6]);
        Integer i =nrep.indexOf("Numéro de réparation ");
        System.out.println(i);
        nrep = nrep.substring(i+21,i+32);*/
        System.out.println(nrep[6]);
        
        String requete0="SELECT UPS from réparation WHERE N_REP='"+nrep[6]+"'";
        
        //System.out.println(requete);
        try{stm=maConnexion.get_connexion().createStatement();
            rs=stm.executeQuery(requete0);
            while (rs.next()){
            if (rs.getString("UPS").equals("")){
                result=nrep[6];
                //System.out.println(result);
                String requete="UPDATE réparation SET UPS='"+track+"' WHERE N_REP='"+result+"'";
                stm=maConnexion.get_connexion().createStatement();
                stm.executeUpdate(requete);
                
            }
            else {result="Déjà renseigné";}
            }
        }
          
        catch(SQLException e){
            System.err.println(e);
            java.awt.Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, e);}
        }
        catch (TimeoutException e1){
            result="Time out";
        }
        //div.loading:nth-child(2)
        
        driver.findElement(By.cssSelector("#rcmbtn106")).click();
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("#quicksearchbox")));
        try {
                Thread.sleep(4000);}
                catch (InterruptedException e) {
                }
        System.out.println(result);
        return result;
        
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Integer CPT=trackings.getLineCount();
        String track;
        String etat="";
        Integer i;
        Integer j;
        
        
        String [] Ligne= trackings.getText().split("\n");
        //RESULTAT.removeAll();
        if (trackings.getText().endsWith("\n"))
            {CPT=CPT-1;
            System.out.println("Nbr de ligne : "+CPT);}
        for (i=0;i<CPT;i++)
        {   lab.removeAll();
             lab.setIcon(loader);
             lab.paintImmediately(lab.getBounds ());
             lab.update(lab.getGraphics());
            trackings.setText("");
            trackings.paintImmediately(trackings.getBounds ());
            trackings.update(trackings.getGraphics());
            for (j=0;j<i;j++)
                {trackings.append(Ligne[j]+"\n"); trackings.paintImmediately(trackings.getBounds ());
            trackings.update(trackings.getGraphics());}
            track=Ligne[i];
                if((track.length() != 18) )
                       {
                        Ligne[i]=Ligne[i]+"  :  "+"Format incorrect";
                        }
            
                else {Ligne[i]=Ligne[i]+"  :  "+verif(track)+etat;}
            
           
            //RESULTAT.append(Ligne[i]+"\n"); 
            
            trackings.append(Ligne[i]+"\n"); trackings.paintImmediately(trackings.getBounds ());
            trackings.update(trackings.getGraphics());
            etat="";
            for (j=i+1;j<CPT;j++)
                {trackings.append(Ligne[j]+"\n"); 
            trackings.paintImmediately(trackings.getBounds ());
            trackings.update(trackings.getGraphics());}
            try {
                Thread.sleep(1000);}
                catch (InterruptedException e) {
                }
            
        }
        lab.removeAll();
             lab.setIcon(ok);
             lab.paintImmediately(lab.getBounds ());
             lab.update(lab.getGraphics());
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        trackings.setText("");
        trackings.update(trackings.getGraphics());
        
    }//GEN-LAST:event_jButton2ActionPerformed

           
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tracking_UPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tracking_UPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tracking_UPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tracking_UPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tracking_UPS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bouton_Browser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lab;
    private javax.swing.JTextArea trackings;
    // End of variables declaration//GEN-END:variables
}
